app_groupe:
    resource: "@AppBundle/Controller/GroupeController.php"
    type:     annotation

yomat_catalog:
    resource: "@YomatCatalogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation